"""add local ocr inpaint settings

Revision ID: 013
Revises: 012
Create Date: 2026-01-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013_add_local_ocr_inpaint_settings'
down_revision = '012_add_image_format_to_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_local_ocr_inpaint', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('local_ocr_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('local_inpaint_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('local_inpaint_url')
        batch_op.drop_column('local_ocr_url')
        batch_op.drop_column('use_local_ocr_inpaint')
    # ### end Alembic commands ###
