"""add text_style_extraction_mode column

Revision ID: 38be7ac05f65
Revises: 5f00679d98c9
Create Date: 2026-02-04 22:51:22.024266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38be7ac05f65'
down_revision = '5f00679d98c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('text_style_extraction_mode', sa.String(length=20), nullable=False, server_default='local_cv'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'text_style_extraction_mode')
    # ### end Alembic commands ###



