"""add text_style_extraction_mode

Revision ID: 5f00679d98c9
Revises: 013_add_local_ocr_inpaint_settings
Create Date: 2026-02-04 22:48:41.384989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f00679d98c9'
down_revision = '013_add_local_ocr_inpaint_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



