"""add export settings

Revision ID: c294bfaa0ec2
Revises: 011_add_user_template_thumb
Create Date: 2026-01-21 01:05:12.290436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c294bfaa0ec2'
down_revision = '011_add_user_template_thumb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



