"""add vertex_project_id and vertex_location to settings

Revision ID: ca461cd7d325
Revises: 014_add_layout_analysis
Create Date: 2026-02-12 01:36:48.648661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca461cd7d325'
down_revision = '014_add_layout_analysis'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('vertex_project_id', sa.String(length=200), nullable=True))
    op.add_column('settings', sa.Column('vertex_location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'vertex_location')
    op.drop_column('settings', 'vertex_project_id')
    # ### end Alembic commands ###



